### PR TITLE
Pino prettifier API support

### LINKED ISSUE #25: using pino-colada at "pretty" in pino instance
What would it take to use the 'main' source file (exported function) as the pretty printer when creating a pino instance.  I'm avoiding command-line pipes and using environment variables to control pretty printing.

So something like this....which doesn't work.

```javascript
import pino from 'pino'
import colada from 'pino-colada'
// import serializeError from 'serialize-error'

let pretty = {}
if(process.env.UCI_DEV || process.env.DEBUG) {
  pretty = colada
  // pretty = pino.pretty()
  // pretty.pipe(process.stdout)
}

let LOG = process.env.UCI_LOG || process.env.UCI_DEV || process.env.DEBUG

const logger = pino({
  name: 'UCI',
  enabled: !!LOG,
  safe: true,
  serializers: {
    req: pino.stdSerializers.req,
    res: pino.stdSerializers.res
  }
},pretty)

export default logger
```

### LINKED ISSUE #27: How to use in fastify
Hi,

I got so confused when reading through pino, pino-pretty, pino-colada docs...

I tried this:

```js
const app = fastify({
  logger: {
    level: 'info',
    prettifier: require('pino-colada')
  }
})
```

with no luck.. And I really don't want to do the `|` thing.. I just want the app to print the pretty logs. Is that possible?

### PR DESCRIPTION
**Pull request by kbakba**
closes #25 
closes #27

### CODE REVIEW

**Comment by lrlna** [comment]
hey @kbakba! I'll try to review this PR this week!

**Comment by kbakba** [comment]
ping...

**Comment by ezpuzz** [comment]
I am using this branch for what it's worth.

**Review by lrlna — APPROVED** [review]
Sorry it took so long to hit approve! Thanks for sticking around and waiting!

**Comment by lrlna** [comment]
:package: `1.6.0`

**Comment by lrlna** [comment]
There is also a `2.0.0` that has changes from #33, if y'all are updating already.

**Pull request merged**
